# Generated by Django 6.1.1 on 2026-09-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='source_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('docx', 'Word'), ('txt', 'Text')], max_length=10),
        ),
    ]
