# Generated by Django 6.1.1 on 2026-09-10 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_report_headline_metric_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_label', models.CharField(max_length=200)),
                ('dataset', models.CharField(max_length=200)),
                ('column', models.CharField(max_length=200)),
                ('operator', models.CharField(choices=[('gt', 'Greater than'), ('gte', 'Greater than or equal to'), ('lt', 'Less than'), ('lte', 'Less than or equal to')], max_length=4)),
                ('threshold', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='reports.report')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
