# Generated by Django 6.1.1 on 2026-09-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alertrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='source_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('docx', 'Word'), ('txt', 'Text'), ('json', 'JSON')], max_length=10),
        ),
    ]
