# Generated by Django 6.1.1 on 2026-09-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_report_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
